# Generated by Django 2.0.13 on 2019-09-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=200)),
                ('taken_on', models.DateField(verbose_name='date taken')),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='posts')),
                ('aperture', models.DecimalField(blank=True, choices=[(1.4, '1.4'), (2, '2'), (2.8, '2.8'), (4, '4'), (5.6, '5'), (8, '8'), (11, '11'), (16, '16'), (22, '22')], decimal_places=1, max_digits=3, null=True)),
                ('shutter_speed', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '1/2'), (4, '1/4'), (8, '1/8'), (15, '1/15'), (30, '1/30'), (60, '1/60'), (125, '1/125'), (250, '1/250'), (500, '1/500'), (1000, '1/1000'), (2000, '1/2000'), (4000, '1/4000')], null=True)),
                ('exposure', models.PositiveIntegerField(blank=True, choices=[(100, '100'), (200, '200'), (400, '400'), (800, '800'), (1600, '1600')], null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.UserProfile')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='equipment.Camera')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='equipment.Film')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='equipment.Lens')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='posts.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post'),
        ),
    ]
