# Generated by Django 2.0.13 on 2019-09-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Post',
        ),
    ]
