# Generated by Django 2.0.13 on 2019-09-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190904_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('posted_on', models.DateField(verbose_name='date posted')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Post'),
        ),
    ]
