# Generated by Django 2.0.13 on 2019-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20190904_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
