# Generated by Django 2.0.13 on 2019-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
