# Generated by Django 2.0.13 on 2019-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20190906_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
