# Generated by Django 2.0.13 on 2019-09-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20190906_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
