# Generated by Django 2.0.13 on 2019-09-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('feed', '0018_auto_20190909_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
