# Generated by Django 2.0.13 on 2019-09-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20190909_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
