# Generated by Django 2.0.13 on 2019-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_auto_20190909_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AlterField(
            model_name='post',
            name='aperture',
            field=models.DecimalField(blank=True, choices=[(1.4, '1.4'), (2, '2'), (2.8, '2.8'), (4, '4'), (5.6, '5'), (8, '8'), (11, '11'), (16, '16'), (22, '22')], decimal_places=1, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
